human/urls.py
from django.urls import path
from human.views import HumanListView, HumanDetailView

app_name = 'human'

urlpatterns = [
    path('', HumanListView.as_view(), name='list'),
    path('<int:pk>', HumanDetailView.as_view(), name='detail' )
]

skolni_prvni/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('humans/', include('human.urls')),
    path('rooms/', include('room.urls')),
]

human/models.py
from django.db import models

from room.models import Room


class Human(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    salary = models.IntegerField()
    room = models.ForeignKey(Room, on_delete=models.PROTECT)

    def __str__(self):
        return "%s %s" % (self.name, self.surname)

room/models.py
from django.db import models


class Room(models.Model):
    name = models.CharField(max_length=150)
    number = models.CharField(max_length=10)
    tel = models.CharField(max_length=15)

    def avg_salary(self):
        return self.human_set.aggregate(models.Avg('salary'))['salary__avg']

    def __str__(self):
        return self.name


class Key(models.Model):
    human = models.ForeignKey("human.Human", blank=True, null=True, on_delete=models.SET_NULL)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)

    def __str__(self):
        return "%s - %s" % (self.human, self.room)

human/views.py
from django.views.generic import ListView, DetailView
from human.models import Human


class HumanListView(ListView):
    model = Human


class HumanDetailView(DetailView):
    model = Human

human/templates/human/human_detail.html
{% extends 'base.html' %}

{% block title %}Karta osoby {{ human }}{% endblock %}

{% block content %}
    <h1>Karta osoby: {{ human }}</h1>

    <dl>

    <dt>Jméno</dt>
    <dd>{{ human.name }}</dd>

    <dt>Přijmení</dt>
    <dd>{{ human.surname }}</dd>

    <dt>Pozice</dt>
    <dd>{{ human.position }}</dd>

    <dt>Mzda</dt>
    <dd>{{ human.salary }}</dd>

    <dt>Místnost</dt>
    <dd><a href="{% url 'room:detail' human.room_id %}">{{ human.room }}</a></dd>

    <dt>Klice</dt>
    {% for key in human.key_set.all %}
        <dd><a href="{% url 'room:detail' key.room_id %}">{{ key.room }}</a></dd>
    {% empty %}
        <dd>Nema zadne klice</dd>
    {% endfor %}


    </dl>
{% endblock %}

human/templates/human/human_list.html
{% extends 'base.html' %}

{% block title %}Seznam lidí{% endblock %}

{% block content %}
    <h1>Humans</h1>

    {% if object_list %}
    <table>
    <thead><tr>
        <th>Jméno</th>
        <th>Místnost</th>
        <th>Telefon</th>
        <th>Pozice</th>
    </tr></thead>
    <tbody>
    {% for human in object_list %}
        <tr>
            <td><a href="{% url 'human:detail' human.id %}">{{ human }}</a></td>
            <td>{{ human.room }}</td>
            <td>{{ human.room.tel }}</td>
            <td>{{ human.position }}</td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
    {% else %}
        <p>Ještě žádní lidé</p>
    {% endif %}
{% endblock %}

room/templates/room/room_detail.html
{% extends 'base.html' %}

{% block title %}Karta místnosti {{ room }}{% endblock %}

{% block content %}
    <h1>Karta místnosti: {{ room }}</h1>

    <dl>

    <dt>Číslo</dt>
    <dd>{{ room.number }}</dd>

    <dt>Název</dt>
    <dd>{{ room.name }}</dd>

    <dt>Telefon</dt>
    <dd>{{ room.tel }}</dd>

    <dt>Lidé</dt>
    {% for human in room.human_set.all %}
        <dd><a href="{% url 'human:detail' human.id %}">{{ human }}</a></dd>
    {% empty %}
        <dd>Žádní lidé</dd>
    {% endfor %}


    <dt>Prům. mzda</dt>
    <dd>{{ room.avg_salary|floatformat:2}}</dd>


    <dt>Klíče</dt>
    {% for key in room.key_set.all %}
        {% with key.human as human %}
        <dd><a href="{% url 'human:detail' human.id %}">{{ human }}</a></dd>
        {% endwith %}
    {% empty %}
        <dd>Žádné klíče</dd>
    {% endfor %}

    </dl>
{% endblock %}

room/templates/room/room_list.html
{% extends 'base.html' %}

{% block title %}Seznam místností{% endblock %}

{% block content %}
    <h1>Rooms</h1>

    {% if object_list %}
    <table>
    <thead>
    <tr>
        <th>Název</th>
        <th>Číslo</th>
        <th>Telefon</th>
    </tr>
    </thead>
    <tbody>
    {% for room in object_list %}
        <tr>
            <td><a href="{% url 'room:detail' room.id %}">{{ room }}</a></td>
            <td>{{ room.number }}</td>
            <td>{{ room.tel }}</td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
    {% else %}
        <p>Ještě žádní lidé</p>
    {% endif %}
{% endblock %}